import { db, vehicles } from "@workspace/db";

const vehicleData = [
  // --- SUVs ---
  {
    year: 2024, make: "Toyota", model: "RAV4", trim: "XLE",
    mileage: 12400, price: 29825, type: "suv",
    mpg: 37, seats: 5, cargoSpace: 37.6,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "below_market", marketPriceDiff: -1700,
    badge: "Best Match",
    features: ["AWD", "Toyota Safety Sense", "Apple CarPlay", "Heated Seats", "8-inch Touchscreen"],
    matchScore: 94,
  },
  {
    year: 2024, make: "Honda", model: "CR-V", trim: "EX",
    mileage: 5200, price: 30850, type: "suv",
    mpg: 34, seats: 5, cargoSpace: 39.3,
    dealerName: "Honda Marin", dealerDistance: 12.8, dealerRating: 4.5,
    priceStatus: "fair", marketPriceDiff: 0,
    badge: "Most Reliable",
    features: ["FWD", "Honda Sensing", "Wireless CarPlay", "Heated Seats", "Panoramic Roof"],
    matchScore: 88,
  },
  {
    year: 2024, make: "Subaru", model: "Outback", trim: "Premium",
    mileage: 18100, price: 28895, type: "suv",
    mpg: 32, seats: 5, cargoSpace: 32.5,
    dealerName: "Serramonte Subaru", dealerDistance: 8.5, dealerRating: 4.1,
    priceStatus: "below_market", marketPriceDiff: -1305,
    badge: "Great Value",
    features: ["Standard AWD", "EyeSight Safety", "X-Mode Terrain", "Heated Seats"],
    matchScore: 76,
  },
  {
    year: 2024, make: "Mazda", model: "CX-5", trim: "Preferred",
    mileage: 9800, price: 31200, type: "suv",
    mpg: 35, seats: 5, cargoSpace: 30.9,
    dealerName: "Bay Area Mazda", dealerDistance: 6.1, dealerRating: 4.6,
    priceStatus: "fair", marketPriceDiff: 100,
    badge: "Top Rated",
    features: ["AWD", "G-Vectoring Control", "Apple CarPlay", "Bose Audio", "Heated Seats"],
    matchScore: 82,
  },
  {
    year: 2023, make: "Ford", model: "Escape", trim: "SEL",
    mileage: 22000, price: 27450, type: "suv",
    mpg: 33, seats: 5, cargoSpace: 37.5,
    dealerName: "Ford Bay Area", dealerDistance: 9.3, dealerRating: 3.9,
    priceStatus: "below_market", marketPriceDiff: -2200,
    badge: "Budget Pick",
    features: ["AWD", "Ford Co-Pilot360", "SYNC4", "Panoramic Roof"],
    matchScore: 71,
  },
  {
    year: 2023, make: "Honda", model: "Pilot", trim: "EX-L",
    mileage: 28000, price: 38500, type: "suv",
    mpg: 28, seats: 8, cargoSpace: 52.0,
    dealerName: "Honda Marin", dealerDistance: 12.8, dealerRating: 4.5,
    priceStatus: "below_market", marketPriceDiff: -2000,
    badge: "Family Choice",
    features: ["AWD", "3-Row Seating", "Honda Sensing", "Wireless CarPlay", "Hands-Free Access"],
    matchScore: 86,
  },
  {
    year: 2024, make: "Kia", model: "Sportage", trim: "EX",
    mileage: 4400, price: 28750, type: "suv",
    mpg: 33, seats: 5, cargoSpace: 39.6,
    dealerName: "Peninsula Kia", dealerDistance: 18.5, dealerRating: 4.0,
    priceStatus: "below_market", marketPriceDiff: -1400,
    badge: "Best Value",
    features: ["AWD", "Forward Collision Avoidance", "Apple CarPlay", "Heated Seats", "10.25-inch Touchscreen"],
    matchScore: 80,
  },
  {
    year: 2024, make: "Hyundai", model: "Tucson", trim: "N Line",
    mileage: 7200, price: 31900, type: "suv",
    mpg: 32, seats: 5, cargoSpace: 38.7,
    dealerName: "East Bay Hyundai", dealerDistance: 15.2, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -1100,
    badge: "Style Leader",
    features: ["AWD", "Blind-Spot Collision Warning", "Wireless CarPlay", "Heated/Ventilated Seats", "Panoramic Sunroof"],
    matchScore: 78,
  },
  {
    year: 2024, make: "Hyundai", model: "Santa Fe", trim: "SEL",
    mileage: 8100, price: 33500, type: "suv",
    mpg: 29, seats: 5, cargoSpace: 35.5,
    dealerName: "East Bay Hyundai", dealerDistance: 15.2, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -1800,
    badge: "Family SUV",
    features: ["AWD", "Blind-Spot Collision Warning", "Wireless CarPlay", "Heated Seats", "Panoramic Sunroof"],
    matchScore: 81,
  },
  {
    year: 2023, make: "Jeep", model: "Grand Cherokee", trim: "Laredo",
    mileage: 22000, price: 37200, type: "suv",
    mpg: 25, seats: 5, cargoSpace: 37.7,
    dealerName: "East Bay Jeep", dealerDistance: 16.1, dealerRating: 3.7,
    priceStatus: "fair", marketPriceDiff: 400,
    badge: "Trail Rated",
    features: ["4WD", "Quadra-Trac II", "Apple CarPlay", "Adaptive Cruise", "360 Camera", "Selec-Terrain"],
    matchScore: 77,
  },

  // --- Sedans: Toyota Camry ---
  {
    year: 2024, make: "Toyota", model: "Camry", trim: "XSE V6",
    mileage: 11200, price: 34500, type: "sedan",
    mpg: 32, seats: 5, cargoSpace: 15.1,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "fair", marketPriceDiff: 300,
    badge: "Top Sedan",
    features: ["FWD", "Toyota Safety Sense 2.5+", "Apple CarPlay", "Wireless Charging", "JBL Audio"],
    matchScore: 74,
  },
  {
    year: 2022, make: "Toyota", model: "Camry", trim: "XLE",
    mileage: 38100, price: 24800, type: "sedan",
    mpg: 32, seats: 5, cargoSpace: 15.1,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "below_market", marketPriceDiff: -1500,
    badge: "Under $25k",
    features: ["FWD", "Toyota Safety Sense 2.5+", "Apple CarPlay", "Wireless Charging", "Heated Seats"],
    matchScore: 88,
  },
  {
    year: 2021, make: "Toyota", model: "Camry", trim: "LE",
    mileage: 55200, price: 21900, type: "sedan",
    mpg: 32, seats: 5, cargoSpace: 15.1,
    dealerName: "Value Auto Group", dealerDistance: 7.4, dealerRating: 4.3,
    priceStatus: "below_market", marketPriceDiff: -1200,
    badge: "Budget Camry",
    features: ["FWD", "Toyota Safety Sense 2.0", "Apple CarPlay", "Backup Camera", "Bluetooth"],
    matchScore: 82,
  },
  {
    year: 2021, make: "Toyota", model: "Camry", trim: "Hybrid LE",
    mileage: 41000, price: 23200, type: "sedan",
    mpg: 52, seats: 5, cargoSpace: 15.1,
    dealerName: "Peninsula Toyota", dealerDistance: 9.8, dealerRating: 4.5,
    priceStatus: "below_market", marketPriceDiff: -1800,
    badge: "Fuel Saver",
    features: ["FWD", "Hybrid Powertrain", "Toyota Safety Sense 2.0", "Apple CarPlay", "38-52 MPG Combined"],
    matchScore: 91,
  },
  {
    year: 2020, make: "Toyota", model: "Camry", trim: "SE",
    mileage: 67800, price: 18500, type: "sedan",
    mpg: 32, seats: 5, cargoSpace: 15.1,
    dealerName: "Bay City Motors", dealerDistance: 11.2, dealerRating: 3.9,
    priceStatus: "below_market", marketPriceDiff: -2100,
    badge: "High Value",
    features: ["FWD", "Toyota Safety Sense 2.0", "Apple CarPlay", "Sport Trim", "Lane Departure Warning"],
    matchScore: 76,
  },

  // --- Sedans: Honda Accord ---
  {
    year: 2023, make: "Honda", model: "Accord", trim: "Hybrid EX",
    mileage: 18200, price: 27900, type: "sedan",
    mpg: 44, seats: 5, cargoSpace: 16.7,
    dealerName: "Honda Marin", dealerDistance: 12.8, dealerRating: 4.5,
    priceStatus: "fair", marketPriceDiff: -400,
    badge: "Hybrid Pick",
    features: ["FWD", "Hybrid Powertrain", "Honda Sensing", "Wireless CarPlay", "Heated Front Seats", "44 City MPG"],
    matchScore: 87,
  },
  {
    year: 2022, make: "Honda", model: "Accord", trim: "Sport",
    mileage: 29500, price: 24500, type: "sedan",
    mpg: 33, seats: 5, cargoSpace: 16.7,
    dealerName: "Honda Marin", dealerDistance: 12.8, dealerRating: 4.5,
    priceStatus: "below_market", marketPriceDiff: -1900,
    badge: "Sport Sedan",
    features: ["FWD", "Honda Sensing", "Apple CarPlay", "Heated Front Seats", "19-inch Sport Wheels", "192-hp Turbo"],
    matchScore: 89,
  },
  {
    year: 2021, make: "Honda", model: "Accord", trim: "EX-L",
    mileage: 44000, price: 22800, type: "sedan",
    mpg: 33, seats: 5, cargoSpace: 16.7,
    dealerName: "South Bay Honda", dealerDistance: 19.5, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -2400,
    badge: "Loaded Accord",
    features: ["FWD", "Honda Sensing", "Wireless CarPlay", "Leather Seats", "Heated/Ventilated Seats", "Sunroof"],
    matchScore: 85,
  },

  // --- Sedans: Honda Civic ---
  {
    year: 2024, make: "Honda", model: "Civic", trim: "EX",
    mileage: 2800, price: 24900, type: "sedan",
    mpg: 36, seats: 5, cargoSpace: 14.8,
    dealerName: "Honda Marin", dealerDistance: 12.8, dealerRating: 4.5,
    priceStatus: "fair", marketPriceDiff: 300,
    badge: "Almost New",
    features: ["FWD", "Honda Sensing", "Wireless CarPlay", "Heated Front Seats", "Sunroof", "Remote Start"],
    matchScore: 84,
  },
  {
    year: 2023, make: "Honda", model: "Civic", trim: "Sport",
    mileage: 14200, price: 22400, type: "sedan",
    mpg: 36, seats: 5, cargoSpace: 14.8,
    dealerName: "South Bay Honda", dealerDistance: 19.5, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -1100,
    badge: "Fun to Drive",
    features: ["FWD", "Honda Sensing", "Wireless CarPlay", "Sport Exhaust", "18-inch Wheels", "9-inch Touchscreen"],
    matchScore: 86,
  },

  // --- Sedans: Toyota Corolla ---
  {
    year: 2024, make: "Toyota", model: "Corolla", trim: "XSE",
    mileage: 4500, price: 24200, type: "sedan",
    mpg: 35, seats: 5, cargoSpace: 13.1,
    dealerName: "Peninsula Toyota", dealerDistance: 9.8, dealerRating: 4.5,
    priceStatus: "below_market", marketPriceDiff: -900,
    badge: "New Corolla",
    features: ["FWD", "Toyota Safety Sense 3.0", "Wireless CarPlay", "Sport Trim", "18-inch Wheels", "LED Headlights"],
    matchScore: 83,
  },
  {
    year: 2023, make: "Toyota", model: "Corolla", trim: "LE",
    mileage: 18900, price: 19800, type: "sedan",
    mpg: 36, seats: 5, cargoSpace: 13.1,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "fair", marketPriceDiff: -200,
    badge: "Reliable & Cheap",
    features: ["FWD", "Toyota Safety Sense 2.0", "Apple CarPlay", "Adaptive Cruise Control", "Backup Camera"],
    matchScore: 79,
  },

  // --- Sedans: Other ---
  {
    year: 2022, make: "Mazda", model: "Mazda6", trim: "Sport",
    mileage: 31200, price: 21900, type: "sedan",
    mpg: 35, seats: 5, cargoSpace: 14.1,
    dealerName: "Bay Area Mazda", dealerDistance: 6.1, dealerRating: 4.6,
    priceStatus: "below_market", marketPriceDiff: -2200,
    badge: "Sporty Sedan",
    features: ["FWD", "G-Vectoring Control+", "Apple CarPlay", "Sport Seats", "Bose Audio Available"],
    matchScore: 83,
  },
  {
    year: 2023, make: "Mazda", model: "Mazda6", trim: "Grand Touring",
    mileage: 12000, price: 28400, type: "sedan",
    mpg: 34, seats: 5, cargoSpace: 14.1,
    dealerName: "Bay Area Mazda", dealerDistance: 6.1, dealerRating: 4.6,
    priceStatus: "fair", marketPriceDiff: 200,
    badge: "Luxury Feel",
    features: ["FWD", "G-Vectoring Control+", "Wireless CarPlay", "Heated/Ventilated Seats", "Bose 10-Speaker", "Head-Up Display"],
    matchScore: 86,
  },
  {
    year: 2022, make: "Subaru", model: "Legacy", trim: "Sport",
    mileage: 26800, price: 23400, type: "sedan",
    mpg: 35, seats: 5, cargoSpace: 15.1,
    dealerName: "Serramonte Subaru", dealerDistance: 8.5, dealerRating: 4.1,
    priceStatus: "below_market", marketPriceDiff: -1600,
    badge: "AWD Sedan",
    features: ["Standard AWD", "EyeSight Safety", "Apple CarPlay", "11.6-inch Touchscreen", "Sport Trim"],
    matchScore: 84,
  },
  {
    year: 2022, make: "Nissan", model: "Altima", trim: "SR",
    mileage: 33700, price: 21500, type: "sedan",
    mpg: 35, seats: 5, cargoSpace: 15.4,
    dealerName: "Capitol Nissan", dealerDistance: 14.3, dealerRating: 3.8,
    priceStatus: "below_market", marketPriceDiff: -2800,
    badge: "Great Deal",
    features: ["FWD", "ProPilot Assist", "Apple CarPlay", "Sport Package", "Heated Front Seats"],
    matchScore: 77,
  },
  {
    year: 2023, make: "Nissan", model: "Altima", trim: "SL",
    mileage: 17500, price: 24900, type: "sedan",
    mpg: 35, seats: 5, cargoSpace: 15.4,
    dealerName: "Capitol Nissan", dealerDistance: 14.3, dealerRating: 3.8,
    priceStatus: "fair", marketPriceDiff: 100,
    badge: "Fully Loaded",
    features: ["AWD Available", "ProPilot Assist", "Wireless CarPlay", "Leather Seats", "Remote Start", "Bose Audio"],
    matchScore: 80,
  },
  {
    year: 2022, make: "Hyundai", model: "Sonata", trim: "N Line",
    mileage: 24000, price: 23800, type: "sedan",
    mpg: 33, seats: 5, cargoSpace: 16.3,
    dealerName: "East Bay Hyundai", dealerDistance: 15.2, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -1700,
    badge: "Hot Hatch Look",
    features: ["FWD", "SmartSense Safety", "Wireless CarPlay", "Performance Tuning", "19-inch Wheels", "Panoramic Sunroof"],
    matchScore: 81,
  },

  // --- EVs ---
  {
    year: 2024, make: "Tesla", model: "Model Y", trim: "Long Range AWD",
    mileage: 8900, price: 47990, type: "ev",
    mpg: 0, seats: 7, cargoSpace: 76,
    dealerName: "Tesla San Francisco", dealerDistance: 2.1, dealerRating: 4.3,
    priceStatus: "fair", marketPriceDiff: -500,
    badge: "Top EV Pick",
    features: ["Dual Motor AWD", "Autopilot", "17-inch Touchscreen", "Supercharger Access", "OTA Updates"],
    matchScore: 89,
  },
  {
    year: 2023, make: "Chevrolet", model: "Bolt EV", trim: "LT",
    mileage: 21000, price: 23500, type: "ev",
    mpg: 0, seats: 5, cargoSpace: 16.6,
    dealerName: "Chevy Bay Motors", dealerDistance: 8.8, dealerRating: 4.0,
    priceStatus: "below_market", marketPriceDiff: -3000,
    badge: "EV Under $25k",
    features: ["FWD", "259mi Range", "Apple CarPlay", "One-Pedal Driving", "DC Fast Charging", "Regen Braking"],
    matchScore: 85,
  },
  {
    year: 2024, make: "Hyundai", model: "IONIQ 6", trim: "SE Long Range",
    mileage: 6200, price: 38500, type: "ev",
    mpg: 0, seats: 5, cargoSpace: 0,
    dealerName: "East Bay Hyundai", dealerDistance: 15.2, dealerRating: 4.2,
    priceStatus: "below_market", marketPriceDiff: -2100,
    badge: "EV Value",
    features: ["RWD", "361mi Range", "Ultra-Fast 800V Charging", "18-inch Wheels", "HTRAC AWD Available"],
    matchScore: 88,
  },
  {
    year: 2023, make: "Ford", model: "Mustang Mach-E", trim: "Select",
    mileage: 18500, price: 32900, type: "ev",
    mpg: 0, seats: 5, cargoSpace: 59.7,
    dealerName: "Ford Bay Area", dealerDistance: 9.3, dealerRating: 3.9,
    priceStatus: "below_market", marketPriceDiff: -4200,
    badge: "EV Deal",
    features: ["AWD", "270mi Range", "FordPass App", "Apple CarPlay", "Frunk Storage", "OTA Updates"],
    matchScore: 82,
  },

  // --- Trucks ---
  {
    year: 2024, make: "Toyota", model: "Tacoma", trim: "TRD Sport",
    mileage: 3100, price: 41500, type: "truck",
    mpg: 23, seats: 5, cargoSpace: 0,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "fair", marketPriceDiff: 200,
    badge: "Fan Favorite",
    features: ["4WD", "TRD Sport Suspension", "Multi-Terrain Select", "Apple CarPlay", "Crawl Control"],
    matchScore: 85,
  },
  {
    year: 2023, make: "Ford", model: "F-150", trim: "XLT",
    mileage: 19000, price: 39800, type: "truck",
    mpg: 24, seats: 6, cargoSpace: 0,
    dealerName: "SF Ford", dealerDistance: 7.8, dealerRating: 4.1,
    priceStatus: "below_market", marketPriceDiff: -3200,
    badge: "America's Truck",
    features: ["4WD", "Pro Power Onboard", "SYNC 4A", "B&O Audio", "360-Degree Camera"],
    matchScore: 72,
  },
  {
    year: 2022, make: "Toyota", model: "Tundra", trim: "SR5",
    mileage: 34000, price: 43800, type: "truck",
    mpg: 19, seats: 5, cargoSpace: 0,
    dealerName: "SF Toyota Center", dealerDistance: 4.2, dealerRating: 4.8,
    priceStatus: "below_market", marketPriceDiff: -2500,
    badge: "Work Ready",
    features: ["4WD", "V6 Twin Turbo", "Toyota Safety Sense", "Apple CarPlay", "Multi-Terrain Select"],
    matchScore: 79,
  },
];

async function seed() {
  console.log("Seeding vehicles...");
  const existing = await db.select().from(vehicles);
  if (existing.length > 0) {
    console.log(`Already seeded (${existing.length} vehicles). Skipping.`);
    process.exit(0);
  }

  await db.insert(vehicles).values(vehicleData);
  console.log(`Seeded ${vehicleData.length} vehicles.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
