// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carbuddy/ChatInterface.tsx": () => import("../components/mockups/carbuddy/ChatInterface.tsx"),
  "./components/mockups/carbuddy/MobileChat.tsx": () => import("../components/mockups/carbuddy/MobileChat.tsx"),
  "./components/mockups/carbuddy/VehicleCards.tsx": () => import("../components/mockups/carbuddy/VehicleCards.tsx")
};
